# -*- coding: utf-8 -*-
"""GPT2 Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C7vEHfVwNyBathxutmzJ2S1sDBi5YrR1
"""

import torch
import torch.nn as nn
from torch.nn import functional as F

device = 'cuda' if torch.cuda.is_available() else 'cpu'

"""Hyperparameters"""

batch_size = 16
block_size = 32
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0

torch.manual_seed(1337)

"""Data Extraction"""

!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

"""Character Level Tokenization"""

chars = sorted(list(set(text)))
vocab_size = len(chars)
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

"""BPE Tokenization"""

!pip install tokenizers

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer

tokenizer = Tokenizer(BPE())
tokenizer.normalizer = Lowercase()
tokenizer.pre_tokenizer = Whitespace()

trainer = BpeTrainer(
    vocab_size=15000,
    special_tokens=["<PAD>", "<UNK>", "<BOS>", "<EOS>"]
)

tokenizer.train_from_iterator([text], trainer=trainer)

tokenizer.save("shakespeare_tokenizer.json")
tokenizer = Tokenizer.from_file("shakespeare_tokenizer.json")

encode = lambda s: tokenizer.encode(s).ids
decode = lambda ids: tokenizer.decode(ids)

vocab_size = tokenizer.get_vocab_size()

"""Regex Based Tokenization"""

import re

token_pattern = r"\n| |[A-Za-z']+|[^\sA-Za-z']"

tokens = re.findall(token_pattern, text)
vocab = sorted(list(set(tokens)))
vocab_size = len(vocab)

stoi = { t:i for i,t in enumerate(vocab) }
itos = { i:t for i,t in enumerate(vocab) }

def encode(s):
    toks = re.findall(token_pattern, s)
    return [stoi[t] for t in toks]

def decode(l):
    return ''.join([itos[i] for i in l])

"""Train & Test Split"""

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

"""Data Loading"""

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # RANDOM STARTING POINTS FOR SAMPLING TRAINING SEQUENCES
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

"""Training Loss"""

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

"""One Head of Self-Attention"""

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)                                                           # (B, T, C)
        q = self.query(x)                                                         # (B, T, C)
        wei = q @ k.transpose(-2,-1) * C**-0.5                                    # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))              # (B, T, T)
        wei = F.softmax(wei, dim=-1)                                              # (B, T(Q), T(K))
        wei = self.dropout(wei)
        v = self.value(x)                                                         # (B, T, n_head, head_dim)
        out = wei @ v                                                             # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

wei = torch.tensor([
  [1.0, 2.0, 3.0],
  [0.5, 0.2, 0.3]
])
F.softmax(wei, dim=-1)

wei = torch.tensor([
  [1.0, 2.0, 3.0],
  [0.5, 0.2, 0.3]
])
F.softmax(wei, dim=0)

"""Multiple Heads of Self-Attention (Concatenation)"""

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

"""Linear Layer"""

class FeedFoward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

"""Communication followed by Computation"""

class Block(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

"""Bigram Language Model"""

class BigramLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)                               # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb       # (B,T,C)
        x = self.blocks(x)          # (B,T,C)
        x = self.ln_f(x)            # (B,T,C)
        logits = self.lm_head(x)    # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape                  # C = vocab_size
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # CROPPING idx TO THE LAST BLOCK SIZE
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :]       # FOCUS IS ONLY ON THE LAST TIME STEP AS IT CAN PREDICT THE NEXT TOKEN
                                            # DIMENSION IS (B,vocab_size)
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)  # MULTINOMIAL GIVES INDEX OF NEXT TOKEN PROPORTIONAL TO PROBABILITY
                                                                # (B,1)
            idx = torch.cat((idx, idx_next), dim=1) # (B,T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)

print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

"""Generation"""

context = torch.zeros((1, 1), dtype=torch.long, device=device) # (B,T)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))