# -*- coding: utf-8 -*-
"""TASK - 2 (SFT GPT-2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOjLlaoJQUHjnBqydUDW_Asyr_AB7KBG

Install Dependencies
"""

!pip install transformers datasets torch accelerate -q

"""Imports"""

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import GPT2LMHeadModel, GPT2Tokenizer
from datasets import load_dataset
import torch.nn as nn
from torch.optim import AdamW
from torch.cuda.amp import autocast, GradScaler
import os

"""Prompt Formatter"""

def format_prompt(example):
    if example["input"].strip():
        return (
            "Below is an instruction that describes a task, paired with an input that provides further context. "
            "Write a response that appropriately completes the request.\n\n"
            f"### Instruction:\n{example['instruction']}\n\n"
            f"### Input:\n{example['input']}\n\n"
            f"### Response:\n{example['output']}"
        )
    else:
        return (
            "Below is an instruction that describes a task. "
            "Write a response that appropriately completes the request.\n\n"
            f"### Instruction:\n{example['instruction']}\n\n"
            f"### Response:\n{example['output']}"
        )

class AlpacaDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=128):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.samples = []
        for ex in data:
            text = format_prompt(ex)
            enc = tokenizer(
                text,
                truncation=True,
                max_length=max_length,
                padding="max_length",
                return_tensors="pt"
            )
            input_ids = enc["input_ids"].squeeze()
            attention_mask = enc["attention_mask"].squeeze()
            labels = input_ids.clone()
            labels[attention_mask == 0] = -100
            self.samples.append((input_ids, attention_mask, labels))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]

raw = load_dataset("tatsu-lab/alpaca", split="train")
raw = raw.select(range(500))

tokenizer = GPT2Tokenizer.from_pretrained("openai-community/gpt2")
tokenizer.pad_token = tokenizer.eos_token

dataset = AlpacaDataset(raw, tokenizer, max_length=128)
train_size = int(0.9 * len(dataset))
val_size = len(dataset) - train_size
train_set, val_set = torch.utils.data.random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_set, batch_size=1, shuffle=True)
val_loader = DataLoader(val_set, batch_size=1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

torch.backends.cudnn.benchmark = True

model = GPT2LMHeadModel.from_pretrained("openai-community/gpt2")
model.resize_token_embeddings(len(tokenizer))
model = model.to(device)
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

EPOCHS = 1
LR = 5e-5
GRAD_ACCUM_STEPS = 8

optimizer = AdamW(model.parameters(), lr=LR)
scaler = GradScaler()
os.makedirs("./checkpoints", exist_ok=True)

train_losses = []
val_losses = []

for epoch in range(EPOCHS):
    model.train()
    total_train_loss = 0
    optimizer.zero_grad()

    for step, (input_ids, attention_mask, labels) in enumerate(train_loader):
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        with autocast():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss / GRAD_ACCUM_STEPS

        scaler.scale(loss).backward()

        if (step + 1) % GRAD_ACCUM_STEPS == 0:
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad()

        total_train_loss += loss.item() * GRAD_ACCUM_STEPS

        if step % 50 == 0:
            print(f"Epoch {epoch+1} | Step {step}/{len(train_loader)} | Loss: {loss.item()*GRAD_ACCUM_STEPS:.4f}")

        if (step + 1) % 100 == 0:
            model.save_pretrained(f"./checkpoints/step_{step+1}")
            tokenizer.save_pretrained(f"./checkpoints/step_{step+1}")

        if step % 200 == 0:
            torch.cuda.empty_cache()

    avg_train = total_train_loss / len(train_loader)
    train_losses.append(avg_train)

    model.eval()
    total_val_loss = 0
    with torch.no_grad():
        for input_ids, attention_mask, labels in val_loader:
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)
            labels = labels.to(device)
            with autocast():
                outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            total_val_loss += outputs.loss.item()

    avg_val = total_val_loss / len(val_loader)
    val_losses.append(avg_val)
    print(f"\nEpoch {epoch+1} done | Train Loss: {avg_train:.4f} | Val Loss: {avg_val:.4f}\n")

model.save_pretrained("./gpt2-alpaca")
tokenizer.save_pretrained("./gpt2-alpaca")

def generate_response(instruction, input_context="", max_new_tokens=150):
    model.eval()
    if input_context.strip():
        prompt = (
            "Below is an instruction that describes a task, paired with an input that provides further context. "
            "Write a response that appropriately completes the request.\n\n"
            f"### Instruction:\n{instruction}\n\n"
            f"### Input:\n{input_context}\n\n"
            f"### Response:\n"
        )
    else:
        prompt = (
            "Below is an instruction that describes a task. "
            "Write a response that appropriately completes the request.\n\n"
            f"### Instruction:\n{instruction}\n\n"
            f"### Response:\n"
        )

    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
    full_output = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    response = full_output[len(prompt):]
    return response.strip()

print(generate_response("Explain what machine learning is in simple terms."))